### ISSUE TITLE
3.1.0 requires tslib, but it's not specified in dependencies or peerDependencies

### ISSUE THREAD

**Issue by kyle-johnson** [vultix/ts-results#19]
Upgraded from 3.0.0 to 3.1.0 and we now get "not found" errors for `tslib`.

Looks like the addition of multiple exports in `src/index.ts` make `tslib` is a requirement now, as `require("tslib")` shows up in the dist files:

```javascript
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "tslib", "./result", "./option"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var tslib_1 = require("tslib");
    tslib_1.__exportStar(require("./result"), exports);
    tslib_1.__exportStar(require("./option"), exports);
});
```

This package may work without the explicit dependency/peerDependency depending on your choice of npm/yarn/pnpm, flat/hoisted flags, and resolvers within build tools (webpack/rollup/metro/tsc/babel, etc).

(Reviewing the codebase, `rxjs` probably should also be a `peerDependency`, although we don't use the rxjs features.)

**Comment by iamdavidmartin** [comment]
I can't use ts-results with esbuild because of this problem.

I've temporarily solved this by forking the repo and combining results.ts, option.ts and util.ts into the file index.ts. The "export *" is the root cause of the issue when using package managers, and that means this library can't be used with esbuild. In my repo, I've also added `dist` so it can be installed with yarn: `yarn add https://github.com/iamdavidmartin/ts-results`

But yeah, this is quite inconvenient.
