### ISSUE TITLE
Q: how to use get err value no exception

### ISSUE THREAD

**Issue by yuu** [vultix/ts-results#66]
Hi!
Thank you, it's a great library. My logic is using the 'ts-results' library for the return type.

one question need help you.
how to get value for Err type without exception.

below my frontend code.
```
const result = await api.doSomething()
const x = result
  .map(() => ({ isLoading: 'done', error: None }))
  .mapErr(v => ({ isLoading: 'done', error: Some(v) }))

setState(x.unwrap())
```

i want to if api occurred error, change to error state and showing error message by alert or dialog.
but `unwrap()` occurred exception.

sorry my poor english.

Best regards,
yuu

**Comment by tmikus** [comment]
Hi @yuu 

After looking through the documentation I found two ways you could do this:

## Simply use the `val` property
Due to the way this library works, you can simply obtain the value held by the result by simply accessing the `val` property, for example:
```javascript
const result = await api.doSomething()
const x = result
  .map(() => ({ isLoading: 'done', error: None }))
  .mapErr(v => ({ isLoading: 'done', error: Some(v) }))

setState(x.val); // The val holds either the successful or the error state - you can simply grab it
```

## Implement a custom `unwrapOrElse` function
In the Rust implementation of the `Result` type there's a function called [unwrap_or_else](https://doc.rust-lang.org/core/option/enum.Option.html#method.unwrap_or_else), which sadly hasn't made it through to this project.
You could simply implement your own version, for example:
```javascript
function unwrapOrElse(result, func) {
  if (result.ok) {
    return result.val;
  }
  return func(result.val);
}
```
You can then use this function like this:
```javascript
const result = await api.doSomething()
const x = unwrapOrElse(
  result.map(() => ({ isLoading: 'done', error: None })),
  v => ({ isLoading: 'done', error: Some(v) }),
)

setState(x)
```

Either of these options are fine, but I feel like simply using the `val` property is a cleaner solution.

Hope this helps.
Tomasz

**Comment by yuu** [comment]
@tmikus

sorry late response. 
"val" is best solution with my code.
thank you very match!

Best regards,
yuu
